/******************************
*   Amulet of Protection +2   *
******************************/
COPY ~%MOD_FOLDER%/craftable-items/weidu/items/amulets/BZAM14BI.BAM~ ~override/BZAM14BI.BAM~

//make amulet +2
COPY_EXISTING ~AMUL14.ITM~ ~override/BZAML14B.ITM~ //Amulet of Protection +2
    //Patches
        SAY NAME2 @80000
        SAY IDENTIFIED_DESC @80001
        WRITE_LONG 0x34 9000                    // Price
        WRITE_ASCII_TERMINATE 0x3A "BZAM14BI"   // Icon
        WRITE_LONG 0x42 70                      // Lore to Identify
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                check_globals = 1
                match_opcode = 0                // AC Bonus
                parameter1 = 2
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                check_globals = 1
                match_opcode = 33               // Save: Death
                parameter1 = 2
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                check_globals = 1
                match_opcode = 34               // Save: Wands
                parameter1 = 2
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                check_globals = 1
                match_opcode = 35               // Save: Polymorph
                parameter1 = 2
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                check_globals = 1
                match_opcode = 36               // Save: Breath
                parameter1 = 2
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                check_globals = 1
                match_opcode = 37               // Save: Spell
                parameter1 = 2
        END