/*********************
*   Kiel's Helm +1   *
*********************/
// Kiel's Helmet +1 Inventory BAM
COPY ~%MOD_FOLDER%/craftable-items/weidu/items/helmets/BZHE14AI.BAM~ ~override/BZHE14AI.BAM~

COPY_EXISTING ~HELM14.ITM~ ~override/BZHLM14A.ITM~ //Kiel's Helmet -> +1
    //Patches
        SAY NAME2 @60000
        SAY IDENTIFIED_DESC @60001
        WRITE_ASCII_TERMINATE 0x3A "BZHE14AI"   // Icon
        WRITE_LONG 0x34 6500                    // Price
        WRITE_LONG 0x42 90                      // Lore to Identify
        LPF ~ADD_ITEM_EQEFFECT~         // AC Bonus
            INT_VAR
                opcode = 0              // Type: AC Bonus
                target = 1              // self
                power = 0
                parameter1 = 1          // bonus amount
                parameter2 = 0          // flat bonus, all types
                timing = 2              // Timing Mode: Instant/While equipped
                resist_dispel = 0       // Natural/nonmagical
                duration = 0
                probability1 = 100
                probability2 = 0
                dicenumber = 0
                dicesize = 0
                savingthrow = 0
                savebonus = 0
                special = 0             // enchantment
                insert_point = "-1"     // add to end
            STR_VAR
                resource = ~~           // unused
        END