/*****************************************
*   Light Crossbow +2: The Army Scythe   *
*****************************************/
COPY ~%MOD_FOLDER%/craftable-items/weidu/items/crossbows/BZXB06BI.BAM~ ~override/BZXB06BI.BAM~
COPY_EXISTING ~XBOW06.ITM~ ~override/BZXBW06B.ITM~   //Crossbow of speed +1 -> +2
    //Patches
        SAY NAME2 @130000
        SAY IDENTIFIED_DESC @130001
        WRITE_LONG 0x34 16000                   // Price
        WRITE_ASCII_TERMINATE 0x3A "BZXB06BI"   // Icon
        WRITE_LONG 0x42 80                      // Lore to Identify
        WRITE_LONG 0x60 2                       // Enchantment
        LPF ~ALTER_ITEM_HEADER~
            INT_VAR
                header = 1
                thac0_bonus = 2
                damage_bonus = 2
            STR_VAR
                icon = ~BZXB06BI~       // icon to display for ranged
        END
