/*****************************
*   Mace +2: The Stupefier   *
*****************************/
COPY ~%MOD_FOLDER%/craftable-items/weidu/items/maces/BZMA41BI.BAM~ ~override/BZMA41BI.BAM~

COPY_EXISTING ~BLUN41.ITM~ ~override/BZMAC41B.ITM~ //Mace +1 Stupefier -> +2
    //Patches
        SAY NAME2 @90000
        SAY IDENTIFIED_DESC @90001
        WRITE_ASCII_TERMINATE 0x3A "BZMA41BI"   // Icon
        WRITE_LONG 0x34 4500                    // Price
        WRITE_LONG 0x42 60                      // Lore to Identify
        WRITE_LONG 0x60 2                       // Enchantment
        LPF ~ALTER_ITEM_HEADER~
            INT_VAR
                header = 1
                thac0_bonus = 2
                damage_bonus = 3
            STR_VAR
                icon = ~BZMA41BI~       // icon to display for melee
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                //NOTE: Match all opcodes
                check_headers = 1
                probability1 = 15
                savebonus = "-1"
        END


