/************************
*   Kiel's Buckler +1   *
************************/
// Kiel's Buckler +1 Inventory BAM
COPY ~%MOD_FOLDER%/craftable-items/weidu/items/shields/BZSH20AI.BAM~ ~override/BZSH20AI.BAM~

//Kiel's Buckler -> +1
COPY_EXISTING ~SHLD20.ITM~ ~override/BZSH20A.ITM~
    //Patches
        SAY NAME2 @70000
        SAY IDENTIFIED_DESC @70001
        WRITE_ASCII_TERMINATE 0x3A "BZSH20AI"   // Icon
        WRITE_LONG 0x34 4500                    // Price
        WRITE_LONG 0x42 90                      // Lore to Identify
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                header = 1
                check_globals = 1
                match_opcode = 0                // AC bonus
                parameter1 = 2                  // AC bonus of 2
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                header = 2
                check_globals = 1
                match_opcode = 0                // AC bonus
                parameter1 = "-2"               // AC bonus of -2
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                header = 3
                check_globals = 1
                match_opcode = 0                // AC bonus
                parameter1 = "-2"               // AC bonus of -2
        END


/***************************
*   Buckley's Buckler +1   *
***************************/
// Buckley's Buckler +1 Inventory BAM
COPY ~%MOD_FOLDER%/craftable-items/weidu/items/shields/BZSH33AI.BAM~ ~override/BZSH33AI.BAM~

//Buckley's Buckler -> +1
COPY_EXISTING ~SHLD33.ITM~ ~override/BZSH33A.ITM~
    //Patches
        SAY NAME2 @70100
        SAY IDENTIFIED_DESC @70101
        WRITE_ASCII_TERMINATE 0x3A "BZSH33AI"   // Icon
        WRITE_LONG 0x34 2800                    // Price
        WRITE_LONG 0x42 70                      // Lore to Identify
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                header = 1
                check_globals = 1
                match_opcode = 0                // AC bonus
                parameter1 = 2                  // AC bonus of 2
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                header = 2
                check_globals = 1
                match_opcode = 0                // AC bonus
                parameter1 = "-2"               // AC bonus of -2
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                header = 3
                check_globals = 1
                match_opcode = 0                // AC bonus
                parameter1 = "-2"               // AC bonus of -2
        END