/************************************
*   War Hammer +2: Hammer of Dawn   *
************************************/
COPY ~%MOD_FOLDER%/craftable-items/weidu/items/hammers/BZHM13BI.BAM~ ~override/BZHM13BI.BAM~
COPY_EXISTING ~HAMM13.ITM~ ~override/BZHAM13B.ITM~ //Hammer of Dawn +1 -> +2
    //Patches
        SAY NAME2 @120000
        SAY IDENTIFIED_DESC @120001
        WRITE_ASCII_TERMINATE 0x3A "BZHM13BI"   // Icon
        WRITE_LONG 0x34 4500                    // Price
        WRITE_LONG 0x42 60                      // Lore to Identify
        WRITE_LONG 0x60 2                       // Enchantment
        LPF ~ALTER_ITEM_HEADER~
            INT_VAR
                header = 1
                thac0_bonus = 2
                damage_bonus = 3
            STR_VAR
                icon = ~BZHM13BI~       // icon to display for melee
        END
        LPF ~ALTER_ITEM_EFFECT~
            INT_VAR
                check_headers = 1
                match_opcode = 235      // Wing Buffet
                probability1 = 15
        END
